name: CD Deploy UI

description: Deploy the Blazor UI to Azure App Service.

inputs:
  app-service-name:
    description: Azure App Service name.
    required: true
  dotnet-version:
    description: Dotnet SDK version to use.
    required: false
    default: 9.0.x
  publish-path:
    description: Output path for dotnet publish.
    required: false
    default: ./publish
  azure-credentials:
    description: Azure service principal credentials JSON.
    required: true

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Publish UI
      shell: bash
      run: |
        dotnet restore src/Agentic.DevOps.UI/Agentic.DevOps.UI.csproj
        dotnet publish src/Agentic.DevOps.UI/Agentic.DevOps.UI.csproj --configuration Release --output ${{ inputs.publish-path }}

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure-credentials }}

    - name: Deploy to App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ inputs.app-service-name }}
        package: ${{ inputs.publish-path }}
